config/routes.rb
MycardServerHttp::Application.routes.draw do
  get "stream/index"

  resources :referees

  resources :enrolls

  resources :matches

  resources :tournaments

  get "captcha/show"

  resources :attachments

  resources :moderators

  resources :servers

  resources :libraries

  resources :decks

  get "rooms/index"

  get "mycard/update"
  get "mycard/download"

  root :to => "mycard#index"
  
  resources :duels do
    get 'user1_deck.:format' => "duels#user1_deck"
    get 'user2_deck.:format' => "duels#user2_deck"
  end
  resources :cards
  get 'search/cards' => 'cards#search'
  resources :users do
    resources :duels
    resources :cards
  end
  resources :boards
  resources :topics
  resources :rooms
  get 'topics/control' => "topics#control", :as => :control_topics
  resources :posts
  resources :users do
    get 'pms' => "pms#index"
    get 'topics' => "users#topic"
  end
  get 'theme/:theme' => 'users#theme', :as => :theme
  match 'login' => 'users#login'
  get 'logout' => 'users#logout'
  get 'register' => 'users#new'
  resources :pms
  resources :links
  resources :moderations
  resources :stream
  match "/captcha" => "captcha#show"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/topic.rb
#encoding: UTF-8
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :board, :foreign_key => :category_id
  has_many :posts
  accepts_nested_attributes_for :posts
  validates :name,  :presence => true
  validates :user_id, :numericality => { :greater_than => 0, :message => "发帖请先登录" }
  default_scope where(:deleted => false)
  
  alias category board
  def user
    super || User::Guest
  end
  def to_s
    result = name
    if color?
      result = "<font color=\"#{color}\">#{result}</font>"
    end
    result = "<a href=\"/topics/#{id}\">#{result}</a>".html_safe
  end
  def floor
  	  self.posts.order('displayorder DESC').first.displayorder + 1
  end
  def color
    '#' << (highlight & 0xFFFFFF).to_s(16).rjust(6, "0")
  end
  def color?
    !(highlight & 0xFFFFFF).zero?
  end
end

app/controllers/topics_controller.rb
#encoding: UTF-8
class TopicsController < ApplicationController
  #  ApplicationHelper::addon_header.push "zh_header"
  #  ApplicationHelper::addon_top.push "zh_top"
  #  ApplicationHelper::addon_footer.push "zh_footer"
  
=begin
  查看主题: GET /topic/1
  发表主题：POST /topic/1
  编辑主题: PUT /topic/1
  
  
  主题管理：
  删除：/topic/control?id=1&deleted=1
  反删除：/topic/control?id=1&deleted=0
  置顶 3 /topic/control?id=1&displayorder=3
  沉底 /topic/control?id=1&displayorder=-1
  恢复正常排序 /topic/control?id=1&displayorder=-1
  高亮 /topic/control?id=1&highlight=  //TODO
  精华 3 /topic/control?id=1&digest=3
  取消精华 /topic/control?id=1&digest=0
  锁定 /topic/control?id=1&locked=1
  打开 /topic/control?id=1&locked=0
  移动 /topic/control?id=1&category_id=1
  分类 /topic/control?id=1&type_id=1
  以上操作可以多重进行
  例如把1,2,3号id的主题进行精华3和置顶1
  /topic/control?id=1,2,3&digest=3&displayorder=1
  
=end
  
  
=begin  
  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end
=end
  # GET /topics/1
  # GET /topics/1.xml
  def show
    @page = params[:page] && !params[:page].empty? ? params[:page].to_i : 1
    @topic = Topic.find(params[:id])
    @actions = [@topic.category, @topic]
    @posts = Post.find_all_by_topic_id(params[:id], :offset => 10*@page-10, :limit => 10, :order => :displayorder)

    @topic.update_attribute(:viewnum, @topic.viewnum + 1)
    @current_user.update_attribute(:viewnum, @current_user.viewnum + 1)
    
    @post = Post.new
    @post.topic = @topic
    @post.attachments.build
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => params[:page] && !params[:page].empty? ? @posts : @topic }
    end
  end

  # GET /forum/id/new
  # GET /forum/id/new.xml
  def new
    @topic = Topic.new
    @post = Post.new(topic: @topic)
    @post.attachments.build
    @actions = [@topic.category, @topic, "发表主题"]
    @actions = ["发表主题"]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
    @post = @topic.posts.first
    @post.attachments.build
    @actions = [@topic.category, @topic, "编辑"]
  end

  # POST /board/id
  # POST /board/id.xml
  def create
    @topic = Topic.new(params[:topic])
    @topic.user = @current_user
    @topic.displayorder = 0
    @topic.posts.first.displayorder = 1
    @topic.posts.first.user = @current_user
    @actions = [@topic.category, @topic, "发表主题"]
    respond_to do |format|
      if params[:captcha] == session[:captcha] and @topic.save
        format.html { redirect_to(@topic, :notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        @topic.errors[:base] << ("验证码错误") if params[:captcha] != session[:captcha]
        @post = @topic.posts.first
        @post.attachments.build
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])
    @actions = [@topic.category, @topic, "编辑"]
    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        @post = @topic.posts.first
        @post.attachments.build
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end
=begin
  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
=end
  

  Data_Control = ['deleted', 'displayorder', 'highlight', 'digest', 'locked', 'category_id', 'type_id']
  def control
    if params['id']
      id = params['id'].split(/,/)
      return if id.empty?
    else
      return
    end
    data_control = {}
    Data_Control.each do |key| #喵你妹的Hash不带交集运算
      data_control[key] = params[key] if params[key]
    end
    unless data_control.empty?
      @topics_size = Topic.update_all(data_control, {:id => id})
    end
    if params['merge']
      #TODO
    end
    if params['split']
      #TODO
    end
    respond_to do |format|
      format.html { redirect_to(:back, :notice => 'Topic was successfully updated.') }
      format.xml  { render :xml => @topics_size }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def control_topic_path(topic, data_control)
    "/topic/control?id=#{topic.is_a?(Topic) ? topic.id : topic.collect{|t|t.id}.join(',')}&#{data_control.collect{|key, value|"#{key}=#{value}"}.join('&')}"
  end
end

app/views/topics/_editor.html.erb
<% name ||= 'post[content]' %>
<% content ||= nil %>
<!-- 文本框name的值，这句看不明白的话不用更改，直接调用name即可 -->

<div class="editor">
    <%= text_area_tag name, content %>
    <!-- content是个传入的参数，初始内容 -->
</div>

app/views/topics/_editor_lite.html.erb
<% name ||= 'post[content]' %>
<% content ||= nil %>
<!-- 文本框name的值，看不明白的话不用更改，指定文本框name的时候直接调用name即可 -->

<div class="editor_lite">
  <%= text_area_tag name, content, :id => :fastpostmessage, :rows => 5, :cols => 80,  :tabindex => 4, :class => :txtarea %>
  <!--id和class直接对应于HTML码，从DZ的主题上遗留下来的，应该修改-->
</div>
<script type="text/javascript">
$(document).ready(function()	{
	$('#fastpostmessage').markItUp(mySettings);
});
</script>

app/views/topics/_form.html.erb
<%= form_for(@topic, :html => { :multipart => true, :id => :topic }) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%=t 'activerecord.errors.template.header', :count => @topic.errors.size, :model => @topic.class.model_name.human %></h2>
      <h4><%=t 'activerecord.errors.template.body', :count => @topic.errors.size %></h4>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :board %><br />
    <!--<%= f.select :category_id, Board.all.collect{|board|[board.name, board.id]} %>-->
    <%= f.hidden_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field" style="margin-left: 30px">
    <%= f.fields_for :posts, @post do |post_fields| %>
      <%= post_fields.text_area :content, :id => :fastpostmessage %>
      <div class="field">
        <%= post_fields.label "附件" %><br />
        <%= post_fields.fields_for :attachments do |attachment_form| %>
          <div class="asset field">
            <% if attachment_form.object.data.exists? %>
              <%= attachment_form.object.data.original_filename %>
            <% else %>
              <%= attachment_form.file_field :data %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <!--<div class="field">
  <%= f.label :readperm %><br />
  <%= f.text_field :readperm %>
  </div>
  <div class="field">
  <%= f.label :private %><br />
  <%= f.check_box :private %>
  </div>-->
  <div class="ajax-fc-container" style="margin-left: 30px">You must enable javascript to see captcha here!</div>
  <%= f.hidden_field :displayorder %>
  <%= f.hidden_field :category_type %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
  $(document).ready(function()	{
    $('#fastpostmessage').markItUp(mySettings);
  });
</script>
<script type="text/javascript" charset="utf-8">
  $(function() {
    $(".ajax-fc-container").captcha({
      borderColor: "silver",
      text: "验证码：请把<span>scissors</span>拖进圆圈"
    });
  });
</script>

app/views/topics/control.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= @info.inspect %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>User</th>
    <th>Type</th>
    <th>Board</th>
    <th>Name</th>
    <th>Displayorder</th>
    <th>Views</th>
    <th>Readperm</th>
    <th>Notice</th>
    <th>Reverse</th>
    <th>Private</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.user %></td>
    <td><%= topic.type %></td>
    <td><%= topic.board %></td>
    <td><%= topic.name %></td>
    <td><%= topic.displayorder %></td>
    <td><%= topic.views %></td>
    <td><%= topic.readperm %></td>
    <td><%= topic.notice %></td>
    <td><%= topic.reverse %></td>
    <td><%= topic.private %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>