config/routes.rb
MycardServerHttp::Application.routes.draw do
  get "stream/index"

  resources :referees

  resources :enrolls

  resources :matches

  resources :tournaments

  get "captcha/show"

  resources :attachments

  resources :moderators

  resources :servers

  resources :libraries

  resources :decks

  get "rooms/index"

  get "mycard/update"
  get "mycard/download"

  root :to => "mycard#index"
  
  resources :duels do
    get 'user1_deck.:format' => "duels#user1_deck"
    get 'user2_deck.:format' => "duels#user2_deck"
  end
  resources :cards
  get 'search/cards' => 'cards#search'
  resources :users do
    resources :duels
    resources :cards
  end
  resources :boards
  resources :topics
  resources :rooms
  get 'topics/control' => "topics#control", :as => :control_topics
  resources :posts
  resources :users do
    get 'pms' => "pms#index"
    get 'topics' => "users#topic"
  end
  get 'theme/:theme' => 'users#theme', :as => :theme
  match 'login' => 'users#login'
  get 'logout' => 'users#logout'
  get 'register' => 'users#new'
  resources :pms
  resources :links
  resources :moderations
  resources :stream
  match "/captcha" => "captcha#show"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post
  has_attached_file :data
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.erb
<li>
  <%= link_to attachment.data.original_filename, attachment.data.url %>
  <% case %>
  <% when attachment.data.content_type[0, 5] == "image" %>
      <div><%= image_tag attachment.data.url %></div>
  <% else %>
      <% case File.extname attachment.data.original_filename %>
      <% when ".yrp" %>
          <span><%= link_to "播放", 'mycard://' + request.env['HTTP_HOST'] + URI.escape(attachment.data.url nil, timestamp: false ) %></span>
      <% when ".ydk" %>
          <span><%= link_to "编辑", 'mycard://' + request.env['HTTP_HOST'] + URI.escape(attachment.data.url nil, timestamp: false ) %></span>
      <% when ".deck" %>
          <span><%= link_to "编辑", 'mycard://' + request.env['HTTP_HOST'] + URI.escape(attachment.data.url nil, timestamp: false ) %></span>
      <% end %>
  <% end %>
</li>

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_file_name %><br />
    <%= f.text_field :data_file_name %>
  </div>
  <div class="field">
    <%= f.label :data_content_type %><br />
    <%= f.text_field :data_content_type %>
  </div>
  <div class="field">
    <%= f.label :data_file_size %><br />
    <%= f.number_field :data_file_size %>
  </div>
  <div class="field">
    <%= f.label :data_updated_at %><br />
    <%= f.datetime_select :data_updated_at %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Data file name</th>
    <th>Data content type</th>
    <th>Data file size</th>
    <th>Data updated at</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= attachment.data_file_name %></td>
    <td><%= attachment.data_content_type %></td>
    <td><%= attachment.data_file_size %></td>
    <td><%= attachment.data_updated_at %></td>
    <td><%= attachment.post_id %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data file name:</b>
  <%= @attachment.data_file_name %>
</p>

<p>
  <b>Data content type:</b>
  <%= @attachment.data_content_type %>
</p>

<p>
  <b>Data file size:</b>
  <%= @attachment.data_file_size %>
</p>

<p>
  <b>Data updated at:</b>
  <%= @attachment.data_updated_at %>
</p>

<p>
  <b>Post:</b>
  <%= @attachment.post_id %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>