config/routes.rb
MycardServerHttp::Application.routes.draw do
  get "stream/index"

  resources :referees

  resources :enrolls

  resources :matches

  resources :tournaments

  get "captcha/show"

  resources :attachments

  resources :moderators

  resources :servers

  resources :libraries

  resources :decks

  get "rooms/index"

  get "mycard/update"
  get "mycard/download"

  root :to => "mycard#index"
  
  resources :duels do
    get 'user1_deck.:format' => "duels#user1_deck"
    get 'user2_deck.:format' => "duels#user2_deck"
  end
  resources :cards
  get 'search/cards' => 'cards#search'
  resources :users do
    resources :duels
    resources :cards
  end
  resources :boards
  resources :topics
  resources :rooms
  get 'topics/control' => "topics#control", :as => :control_topics
  resources :posts
  resources :users do
    get 'pms' => "pms#index"
    get 'topics' => "users#topic"
  end
  get 'theme/:theme' => 'users#theme', :as => :theme
  match 'login' => 'users#login'
  get 'logout' => 'users#logout'
  get 'register' => 'users#new'
  resources :pms
  resources :links
  resources :moderations
  resources :stream
  match "/captcha" => "captcha#show"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/controllers/mycard_controller.rb
class MycardController < ApplicationController
  layout false
  def index
  end
  def update
    result = []
    version = params[:version]
    loop do
      new_version = false
      Dir.glob('public/mycard/mycard-update-*-*.zip') do |file|
        if file =~ /mycard-update-(.+?)-(.+?).zip/
          if $1 <= version and $2 > version
            version = $2
            result << "http://card.touhou.cc/mycard/#{$&}"
            new_version = true
            break
          end
        end
      end
      if !new_version
        break
      end
    end
    respond_to do |format|
      format.json { render json: result }
    end
  end
  def download
    file = Dir.glob('public/mycard/mycard-*-win32.7z').max
    if file
      file = File.basename(file)
      respond_to do |format|
        format.html {redirect_to "/mycard/#{file}" }
      end
    end
  end
end

app/helpers/mycard_helper.rb
module MycardHelper
end

app/views/mycard/index.html.erb
<!DOCTYPE html>
<head>
  <meta charset="UTF-8"> 

  <link href='http://fonts.googleapis.com/css?family=Nunito:700' rel='stylesheet' type='text/css'>
  <!--[if lt IE 9]><%= javascript_include_tag 'html5shiv' %><![endif]-->
  <%= javascript_include_tag 'application' %>    
  <%= javascript_include_tag 'mycard' %>
  <%= stylesheet_link_tag    'mycard' %>
  <title>Mycard - 萌卡</title>
  <script type="text/javascript">
    jQuery(document).ready(function($) {   
      $('#slider').cycle({   
        fx:    'fade',  //特效           speed:  7500,
        timeout:  7200,
        random:  1
      });
    }); </script>
</head>
<body>
  <header>
    <nav id="nav">
      <a class="nav_logo">MyCard</a>

      <ul class="menu" id="menu">
        <li><%= link_to "在线大厅", rooms_path, :class => "nav_link" %></li>
        <li><%= link_to "竞技场", users_path,:class => "nav_link" %>
          <ul>
            <li><%= link_to "排行榜", users_path, :class => "nav_sub" %></li>
            <li><%= link_to "决斗记录", duels_path, :class => "nav_sub" %></li>
            <li><%= link_to "我的中心", logged? ? @current_user : login_path, :class => "nav_sub" %></li>
          </ul>
        </li>
        
        <li>
          <%= link_to "卡组统计", decks_path, :class => "nav_link" %>
          <ul>
            <li><%= link_to "卡组排行", decks_path, :class => "nav_sub"  %></li>
            <li><%= link_to "单卡排行", cards_path, :class => "nav_sub"  %></li>
          </ul>
        </li>
        <li><%= link_to "论坛", boards_path, :class => "nav_link" %></li>
        <li>
          <%= link_to "《DUELIST》", 'http://www.duelist.cn/', :class => "nav_link" %>
          <ul>
            <li><%= link_to "第一期", 'http://www.duelist.cn/vol.1/', :class => "nav_sub"  %></li>
            <li><%= link_to "第二期", 'http://www.duelist.cn/vol.2/', :class => "nav_sub"  %></li>
            <li><%= link_to "第三期", 'http://www.duelist.cn/vol.3/', :class => "nav_sub"  %></li>
            <li><%= link_to "第四期", 'http://www.duelist.cn/vol.4/online/online-1.html', :class => "nav_sub"  %></li>
            <li><%= link_to "第五期", 'http://www.duelist.cn/vol.5/online/online-1.html', :class => "nav_sub"  %></li>
            <li><%= link_to "SP1", 'http://www.duelist.cn/sp1/online/online-1.html', :class => "nav_sub"  %></li>
            <li><%= link_to "第六期", 'http://www.duelist.cn/vol.6/online/index.html', :class => "nav_sub"  %></li>
            <li><%= link_to "第七期", 'http://www.duelist.cn/vol.7/', :class => "nav_sub"  %></li>
            <li><%= link_to "第八期", 'http://www.duelist.cn/vol.8/reader.html', :class => "nav_sub"  %></li>
          </ul>
        </li>
      </ul>
      <script type="text/javascript">
        var menu=new menu.dd("menu");
        menu.init("menu","menuhover");
      </script>

    </nav>
  </header>
  <div id="main">
    <div id="main_sub">
      <div id="information">
        <div>
          <a class="title">Mycard</a>
          <a class="subtitle">萌卡</a>
          </br>
          <a class="subinc">程序在开发中 bug什么的要淡定哦</a>
          <div id="download">
            <%= link_to t('mycard.download'), mycard_download_path, :class => "download_active" %>
            <a class="download_information">最新版本:<%= Dir.glob('public/mycard/mycard-*-win32.7z').max =~ /mycard\/mycard-(.*)-win32.7z/; $1 %></a>
          </div>
        </div>
      </div>
      <div id="slider">
        <div class="show1"></div>
        <div class="show2"></div>
        <div class="show3"></div>
      </div>
    </div>
  </div>
  <footer>
    <div id="footer1">
      <h2>其他服务</h2>
      <a href="/api">API</a>
      <a href="mailto:zh99998@gmail.com">联系作者</a>
    </div>
    <div id="footer2">
      <h2>合作伙伴</h2>
      <%= render Link.all %>
    </div>
    <div id="footer3">
      <h2>版权申明</h2>
      <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/2.5/cn/"><img alt="知识共享许可协议" src="http://i.creativecommons.org/l/by-nc-sa/2.5/cn/88x31.png" /></a>
      <a rel="license" href="http://www.gnu.org/licenses/gpl-3.0.html"><img alt="知识共享许可协议" src="http://gplv3.fsf.org/gplv3-88x31.png" /></a>
    </div>
  </footer>
</body>