config/routes.rb
MycardServerHttp::Application.routes.draw do
  get "stream/index"

  resources :referees

  resources :enrolls

  resources :matches

  resources :tournaments

  get "captcha/show"

  resources :attachments

  resources :moderators

  resources :servers

  resources :libraries

  resources :decks

  get "rooms/index"

  get "mycard/update"
  get "mycard/download"

  root :to => "mycard#index"
  
  resources :duels do
    get 'user1_deck.:format' => "duels#user1_deck"
    get 'user2_deck.:format' => "duels#user2_deck"
  end
  resources :cards
  get 'search/cards' => 'cards#search'
  resources :users do
    resources :duels
    resources :cards
  end
  resources :boards
  resources :topics
  resources :rooms
  get 'topics/control' => "topics#control", :as => :control_topics
  resources :posts
  resources :users do
    get 'pms' => "pms#index"
    get 'topics' => "users#topic"
  end
  get 'theme/:theme' => 'users#theme', :as => :theme
  match 'login' => 'users#login'
  get 'logout' => 'users#logout'
  get 'register' => 'users#new'
  resources :pms
  resources :links
  resources :moderations
  resources :stream
  match "/captcha" => "captcha#show"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :library
  belongs_to :origin, :polymorphic => true
  has_and_belongs_to_many :cards

  def self.parse(contents, extname)
    side = false
    card_ids = []
    card_sides = []
    case extname.downcase
      when ".ydk"
        card_numbers = []
        contents.each_line do |line|
          line.chomp!
          next if line[0, 1] == "#"
          next side = true if line == "!side"
          number = line.to_i
          next if number == 0
          card_numbers << number
          card_sides << side
        end
        sql = Card.where(number: card_numbers.uniq).select([:id, :number]).order(:id).group(:number).to_sql
        card_number_id = {}
        Deck.connection.execute(sql).each { |id, number| card_number_id[number] = id }
        card_numbers.each do |number|
          id = card_number_id[number]
          if id.nil?
            Card.create(id: number, name: number, number: number)
            card_number_id[number] = number
          end
          card_ids << card_number_id[number]
        end
      when ".deck", ".txt"
        card_names = []
        contents.force_encoding("GBK").encode("UTF-8").each_line do |line|
          line.chomp!
          next side = true if line == "####"
          next side = false if line == "===="
          break if line == "$$$$"
          line =~ /\[(.*)\]/
          name = $1
          card_names << name
          card_sides << side
        end
        sql = Card.where(name: card_names.uniq).select([:id, :name]).order(:id).group(:name).to_sql
        card_name_id = {}
        Deck.connection.execute(sql).each { |id, name| card_name_id[name] = id }
        card_names.each do |name|
          card_ids << card_name_id[name]
        end
    end
    result = Deck.create
    deck_id = result.id
    sql = "INSERT INTO decks_cards (deck_id, card_id, side) VALUES "
    card_sides = card_sides.to_enum
    card_ids.each do |card_id|
      next card_sides.next if card_id.nil?
      sql << "(#{deck_id}, #{card_id}, #{card_sides.next}),"
    end
    sql[-1, 1] = ';'
    Deck.connection.execute(sql)
    result
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  layout 'ygo'
  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(params[:deck])

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :duel_id %><br />
    <%= f.text_field :duel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <tr>
    <th>卡组</th>
    <th>数量</th>
  </tr>
<% Deck.find(:all, select: "*, count(*) as count", group: :category, order: "count DESC").each do |deck| %>
  <tr>
    <td><%= deck.category %></td>
    <td><%= deck.count %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @deck.name %>
</p>

<p>
  <b>String:</b>
  <%= @deck.string %>
</p>

<p>
  <b>Category:</b>
  <%= @deck.category %>
</p>

<p>
  <b>User:</b>
  <%= @deck.user_id %>
</p>

<p>
  <b>Duel:</b>
  <%= @deck.duel_id %>
</p>


<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>